---
swagger: "2.0"
info:
  description: "This is the API for the Waipoua website"
  version: "1.0.0"
  title: "Waipoua"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "chiara.barbera@mail.polimi.it"
host: "waipoua-association.herokuapp.com:8080"
basePath: "/"
tags:
- name: "service"
  description: "Service provided by the association"
- name: "event"
  description: "Event organized by the association; can be relative to a service"
- name: "person"
  description: "Person that has joined the association"
schemes:
- "http"
- "https"
paths:
  /Events:
    get:
      tags:
      - "event"
      summary: "List of events provided by the association "
      operationId: "eventsGET"
      produces:
      - "application/json"
      parameters:
      - name: "limit"
        in: "query"
        description: "The maximum number of items per page"
        required: false
        type: "integer"
      - name: "offset"
        in: "query"
        description: "Pagination offset. Default is 0."
        required: false
        type: "integer"
      responses:
        "200":
          description: "Success. Return the list of events"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Event"
        "404":
          description: "Error. Collection not found."
      x-swagger-router-controller: "Event"
  /Events/{eventId}:
    get:
      tags:
      - "event"
      summary: "List of events provided by the association "
      operationId: "eventSpecificGET"
      produces:
      - "application/json"
      parameters:
      - name: "eventId"
        in: "path"
        description: "Id of the month"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Success. Return the event details"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Event"
        "404":
          description: "Error. Event not found."
      x-swagger-router-controller: "Event"
  /Events/Categories/{categoryId}:
    get:
      tags:
      - "event"
      summary: "List of events provided by the association "
      operationId: "eventsByCateogoryGET"
      produces:
      - "application/json"
      parameters:
      - name: "limit"
        in: "query"
        description: "The maximum number of items per page"
        required: false
        type: "integer"
      - name: "offset"
        in: "query"
        description: "Pagination offset. Default is 0."
        required: false
        type: "integer"
      - name: "categoryId"
        in: "path"
        description: "Month in which the event takes place"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Success. Return the list of events"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Event"
        "404":
          description: "Error. Collection not found."
      x-swagger-router-controller: "Event"
  /Events/Months/{month}:
    get:
      tags:
      - "event"
      summary: "List of events provided by the association in a certain month "
      operationId: "eventsByMonthGET"
      produces:
      - "application/json"
      parameters:
      - name: "limit"
        in: "query"
        description: "The maximum number of items per page"
        required: false
        type: "integer"
      - name: "offset"
        in: "query"
        description: "Pagination offset. Default is 0."
        required: false
        type: "integer"
      - name: "month"
        in: "path"
        description: "Month in which the event takes place"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Success. Return the list of events"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Event"
        "404":
          description: "Error. Collection not found."
      x-swagger-router-controller: "Event"
  /Services:
    get:
      tags:
      - "service"
      summary: "List of services provided by the association "
      operationId: "servicesGET"
      produces:
      - "application/json"
      parameters:
      - name: "limit"
        in: "query"
        description: "The maximum number of items per page"
        required: false
        type: "integer"
      - name: "offset"
        in: "query"
        description: "Pagination offset. Default is 0."
        required: false
        type: "integer"
      responses:
        "200":
          description: "Success. Return the list of services"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Service"
        "404":
          description: "Error. Collection not found."
      x-swagger-router-controller: "Service"
  /Services/{serviceId}:
    get:
      tags:
      - "service"
      summary: "A specific service"
      operationId: "serviceSpecificGET"
      produces:
      - "application/json"
      parameters:
      - name: "serviceId"
        in: "path"
        description: "The id of the service"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Success. Return the required service"
          schema:
            $ref: "#/definitions/Service"
        "404":
          description: "Error. Service not found."
      x-swagger-router-controller: "Service"
  /Services/Category/{categoryId}:
    get:
      tags:
      - "service"
      summary: "A specific service category"
      operationId: "servicesByCategoryGET"
      produces:
      - "application/json"
      parameters:
      - name: "limit"
        in: "query"
        description: "The maximum number of items per page"
        required: false
        type: "integer"
      - name: "offset"
        in: "query"
        description: "Pagination offset. Default is 0."
        required: false
        type: "integer"
      - name: "categoryId"
        in: "path"
        description: "The id of the cateogory"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Success. Return the list of services by category"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Service"
        "404":
          description: "Error. Service not found."
      x-swagger-router-controller: "Service"
  /People:
    get:
      tags:
      - "person"
      summary: "List of the people that joined the association"
      operationId: "peopleGET"
      produces:
      - "application/json"
      parameters:
      - name: "limit"
        in: "query"
        description: "The maximum number of items per page"
        required: false
        type: "integer"
      - name: "offset"
        in: "query"
        description: "Pagination offset. Default is 0."
        required: false
        type: "integer"
      responses:
        "200":
          description: "Success. Return the list of people"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Person"
        "400":
          description: "Invalid ID"
        "404":
          description: "Error. Collection not found."
      x-swagger-router-controller: "Person"
  /People/{personId}:
    get:
      tags:
      - "person"
      summary: "Find person by Id"
      operationId: "peopleSpecificGET"
      produces:
      - "application/json"
      parameters:
      - name: "personId"
        in: "path"
        description: "The id of a person"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Success. Return the person data"
          schema:
            $ref: "#/definitions/Person"
        "400":
          description: "Invalid ID"
        "404":
          description: "Error. Person not found."
      x-swagger-router-controller: "Person"
  /People/Roles/{category_id}:
    get:
      tags:
      - "person"
      summary: "Find list of person by role"
      operationId: "peopleByRoleGET"
      produces:
      - "application/json"
      parameters:
      - name: "limit"
        in: "query"
        description: "The maximum number of items per page"
        required: false
        type: "integer"
      - name: "offset"
        in: "query"
        description: "Pagination offset. Default is 0."
        required: false
        type: "integer"
      - name: "category_id"
        in: "path"
        description: "The id of the role"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Success. Return the list of people by a certain role"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Person"
        "400":
          description: "Invalid ID"
        "404":
          description: "Error. Collection not found."
      x-swagger-router-controller: "Person"
definitions:
  Event:
    type: "object"
    properties:
      event_id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      presentation:
        type: "string"
      date:
        $ref: "#/definitions/Date"
      image:
        $ref: "#/definitions/Image"
      relativeTo:
        $ref: "#/definitions/Service"
      contact:
        $ref: "#/definitions/Person"
      category:
        $ref: "#/definitions/Category"
      location:
        type: "string"
    title: "Event"
    description: "An event of the association"
    example:
      event_id: 1000
      name: "Why is hunting wrong?!"
      presentation: "We'll explain damages of hunting and poaching to the general public."
      date:
        day: 10
        month: 10
        year: 2020
        hour: 18
        minutes: 30
      image:
        - url: "image_jumbotron.jpg"
        - url: "image_icon.jpg"
      relativeTo:
        name: "Animal protection from hunting and poaching"
        presentation: "What we do to fight hunt and poaching."
        image:
          - url: "image_jumbotron.jpg"
          - url: "image_icon.jpg"
          - url: "image_carousel_01.jpg"
          - url: "image_carousel_02.jpg"
          - url: "image_carousel_03.jpg"
        service_id: 17
        category:
          category_id: 0
          name: "Animal protection"
      contact:
        person_id: 4
        name: "Giovanni"
        surname: "De Mattias"
        description: "A passionate biologist."
        image:
          - url: "image_jumbotron.jpg"
          - url: "image_icon.jpg"
        role:
          category_id: 9
          name: "name"
        phone_number: "+39 347 12345678"
        email: "giovanni.demattias@waipoua.org"
      location: "Via Bellagio 51, Milano (Italy)"
      category:
        category_id: 9
        name: "name"
  Category:
    type: "object"
    properties:
      category_id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    example:
      category_id: 9
      name: "name"
  Image:
    type: "object"
    properties:
      url:
        type: "string"
    example:
      url: "image_url.jpg"
  Person:
    type: "object"
    properties:
      person_id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      surname:
        type: "string"
      image:
        $ref: "#/definitions/Image"
      description:
        type: "string"
      role:
        $ref: "#/definitions/Category"
      email:
        type: "string"
      phone_number:
        type: "string"
      services:
        type: array
        items:
          $ref: "#/definitions/Service"
      events:
        type: array
        items:
          $ref: "#/definitions/Event"
    example:
      person_id: 17
      name: "Giovanni"
      surname: "De Mattias"
      description: "A passionate biologist."
      image:
        url: "image_jumbotron.jpg"
      role:
        category_id: 9
        name: "Biolgist"
      phone_number: "+39 347 12345678"
      email: "giovanni.demattias@waipoua.org"
      services:
        - service_id: 4
      events:
        - event_id: 8
  Service:
    type: "object"
    properties:
      service_id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      presentation:
        type: "string"
      image:
        type: "array"
        items:
          $ref: "#/definitions/Image"
      category:
        $ref: "#/definitions/Category"
      event:
        type: "array"
        items:
          $ref: "#/definitions/Event"
      people:
        type: "array"
        items:
          $ref: "#/definitions/People"
    title: "Service"
    description: "A service of the association"
    example:
      name: "Animal protection from hunting and poaching"
      presentation: "What we do to fight hunt and poaching."
      image:
      - url: "image_jumbotron.jpg"
      - url: "image_carousel_01.jpg"
      - url: "image_carousel_02.jpg"
      - url: "image_carousel_03.jpg"
      service_id: 17
      category:
        category_id: 0
        name: "Animal protection"
      people:
        - person_id: 17
      events:
        - event_id: 1000
  Date:
    type: "object"
    properties:
      day:
        type: "integer"
        format: "int64"
      month:
        type: "integer"
        format: "int64"
      year:
        type: "integer"
        format: "int64"
      hour:
        type: "integer"
        format: "int64"
      minutes:
        type: "integer"
        format: "int64"
    title: "Date"
    description: "The date of an event"
    example:
      day: 6
      month: 1
      year: 5
      hour: 17
      minutes: 30
